"""Add is_verified to Organization model

Revision ID: 345777c1299a
Revises: 60df379fa02c
Create Date: 2025-09-09 13:29:38.893064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345777c1299a'
down_revision = '60df379fa02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
