"""Add enhanced notification system with preferences

Revision ID: 7b3f3b5136a4
Revises: 15981bad115c
Create Date: 2025-09-06 21:40:13.023915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3f3b5136a4'
down_revision = '15981bad115c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_welcome', sa.Boolean(), nullable=True),
    sa.Column('email_organization_updates', sa.Boolean(), nullable=True),
    sa.Column('email_contact_messages', sa.Boolean(), nullable=True),
    sa.Column('email_system_announcements', sa.Boolean(), nullable=True),
    sa.Column('email_security_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_bookmark_digest', sa.Boolean(), nullable=True),
    sa.Column('email_reminders', sa.Boolean(), nullable=True),
    sa.Column('inapp_welcome', sa.Boolean(), nullable=True),
    sa.Column('inapp_organization_updates', sa.Boolean(), nullable=True),
    sa.Column('inapp_contact_messages', sa.Boolean(), nullable=True),
    sa.Column('inapp_system_announcements', sa.Boolean(), nullable=True),
    sa.Column('inapp_security_alerts', sa.Boolean(), nullable=True),
    sa.Column('inapp_bookmark_digest', sa.Boolean(), nullable=True),
    sa.Column('inapp_reminders', sa.Boolean(), nullable=True),
    sa.Column('frequency_digest', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('data')
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('email_sent')
        batch_op.drop_column('read_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('notification_type')
        batch_op.drop_column('title')

    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
